env:
  node: true
  es2021: true
  jest/globals: true

extends:
  - airbnb-base
  - prettier

plugins:
  - "@typescript-eslint"
  - jest

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 12
  sourceType: module

settings:
  import/parser:
    "@typescript-eslint/parser": [".ts"]

  import/resolver:
    typescript:
      alwaysTryTypes: true
      project: "./tsconfig.json"

rules:
  no-unused-vars: "off"
  class-methods-use-this: "off"
  arrow-body-style: "off"
  lines-between-class-members: "off"
  import/extensions: "off"
  import/prefer-default-export: "off"
  import/no-extraneous-dependencies: "off"

globals:
  Action: readonly
  Subject: readonly
  Environment: readonly
